spring:
  application:
    name: job-scheduler-api
logging:
  level:
    root: INFO
management:
  endpoints:
    enabled-by-default: true
server:
  port: ${SERVER_PORT:9000}
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    accesslog:
      enables: true
    uri-encoding: UTF-8
    threads:
      max-connections: 8192
      max: 200
      min-spare: 30
kafka:
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic-name: ${KAFKA_JOB_TOPIC:job-task-system-test}
  acks: ${KAFKA_ACKS:all}
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: io.jobscheduler.producer.connector.TaskSerializer