---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.0
    hostname: broker
    container_name: broker
    depends_on:
      - "zookeeper"
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  producer-api:
    container_name: producer-api
    depends_on:
      - "broker"
      - "mongo"
    build:
      context: producer-api
      dockerfile: container_manifests/Dockerfile
      args:
        APPLICATION_ENV: dev
    ports:
      - "9000:9000"

  scheduler:
    container_name: scheduler
    depends_on:
      - "broker"
      - "mongo"
    build:
      context: scheduler
      dockerfile: container_manifests/Dockerfile
      args:
        APPLICATION_ENV: dev

  scheduler-dashboard-api:
    container_name: scheduler-dashboard-api
    depends_on:
      - "mongo"
    build:
      context: scheduler-dashboard-api
      dockerfile: container_manifests/Dockerfile
      args:
        APPLICATION_ENV: dev
    ports:
      - "9001:9001"
