spring:
  application:
    name: job-scheduler
  data:
    mongodb:
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:scheduling-jobs}
      authentication-database: ${MONGO_AUTH_DB:admin}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:example}
      repositories:
        enable: true
      max-size: 3
      min-size: 1
      max-wait-ms: 6000
      max-idle-ms: 6000
  kafka:
    streams:
      application-id: ${KAFKA_JOB_TOPIC:job-task-system}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:broker:9092}
    listener:
      missing-topics-fatal: true
    consumer:
      groupId: ${KAFKA_JOB_TOPIC:job-task-system}
      topic: ${KAFKA_JOB_TOPIC:job-task-system}
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.jobscheduler.scheduler.serde.TaskDeserializer
    properties:
      ssl:
        endpoint:
          identification:
            algorithm: http
logging:
  level:
    root: INFO
  file:
    name: "application.log"
service:
  executor:
    core:
      pool:
        min: 10
        max: 100
        keep-alive: 60
        termination: 20
  thread:
    semaphore:
      count: 20
      fairness: true
task:
  daemon:
    execution:
      interval: 30000
      query:
        start-interval: 10
        elapsed-interval: 50
  schedule:
    execution:
      window-ts: 120
      delta-ts: 5
      high:
        priority-ts: 5
      medium:
        priority-ts: 10