spring:
  application:
    name: job-scheduler-api
management:
  endpoints:
    enabled-by-default: false
server:
  port: ${SERVER_PORT:9000}
kafka:
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic-name: ${KAFKA_JOB_TOPIC:job-task-system}
  acks: ${KAFKA_ACKS:all}
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: io.jobscheduler.producer.connector.TaskSerializer