spring:
  application:
    name: job-scheduler-api
  data:
    mongodb:
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:scheduling-jobs}
      authentication-database: ${MONGO_AUTH_DB:admin}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:example}
      repositories:
        enable: true
      max-size: 3
      min-size: 1
      max-wait-ms: 6000
      max-idle-ms: 6000
management:
  endpoints:
    enabled-by-default: true
logging:
  file:
    name: "application.log"
  level:
    root: INFO
server:
  port: ${SERVER_PORT:9000}
  error:
    include-message: always
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    accesslog:
      enables: true
    uri-encoding: UTF-8
    threads:
      max-connections: 8192
      max: 200
      min-spare: 30
kafka:
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVERS:broker:9092}
  topic-name: ${KAFKA_JOB_TOPIC:job-task-system}
  acks: ${KAFKA_ACKS:all}
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: io.jobscheduler.producer.connector.TaskSerializer
task:
  schedule:
    execution:
      delta-ts: 5